name: Smart Docker Builder

on:
  push:
    branches:
      - '*'

jobs:
  build-changed-dockerfiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Needed for git diff

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Changed Dockerfiles
        run: |
          DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}"
          REPO_NAME=$(basename "${{ github.repository }}")
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
          COMMIT_SHA="${{ github.sha }}"

          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep '^dockerfile/' || true)

          for dockerfile in $CHANGED_FILES; do
            if [[ -f "$dockerfile" ]]; then
              FILE_NAME=$(basename "$dockerfile")
              TAG="${FILE_NAME%.*}"  # e.g., software.Dockerfile > software
              CONTEXT_DIR=$(dirname "$dockerfile")

              IMAGE="$DOCKER_USERNAME/$REPO_NAME"

              echo "  Building image '$IMAGE' with tags:"
              echo "  - $TAG"
              echo "  - $BRANCH_NAME-$TAG-$COMMIT_SHA"

              docker build -f "$dockerfile" "$CONTEXT_DIR" -t "$IMAGE:$TAG" -t "$IMAGE:$BRANCH_NAME-$TAG-$COMMIT_SHA"
              docker push "$IMAGE:$TAG"
              docker push "$IMAGE:$BRANCH_NAME-$TAG-$COMMIT_SHA"

              echo "Pushed $IMAGE:$TAG and $IMAGE:$BRANCH_NAME-$TAG-$COMMIT_SHA"
            fi
          done

