name: GHCR Build Pipeline

on:
  push:
    branches: [main, develop, release*, feature*, bug*]

env:
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        dockerfile:
          - docker/mamba

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHPAT }}

      - name: Normalize tag components
        id: vars
        run: |
          FILE_NAME=$(basename "${{ matrix.dockerfile }}")
          BRANCH=$(echo "${GITHUB_REF##*/}" | tr '[:upper:]' '[:lower:]' | tr '/' '-')
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-8 | tr '[:upper:]' '[:lower:]')
          echo "name=${FILE_NAME}" >> $GITHUB_OUTPUT
          echo "tag1=${{ env.REGISTRY }}/${{ env.REPO }}:${FILE_NAME}-${BRANCH}-latest" >> $GITHUB_OUTPUT
          echo "tag2=${{ env.REGISTRY }}/${{ env.REPO }}:${FILE_NAME}-${BRANCH}-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ steps.vars.outputs.tag1 }}
            ${{ steps.vars.outputs.tag2 }}

