name: GHCR Build Pipeline

on:
  push:
    branches: [main, develop, release*, feature*, bug*]

env:
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        dockerfile:
          - dockerfiles/mamba

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHPAT }}

      - name: Sanitize image reference
        id: vars
        run: |
          FILE_NAME=$(basename "${{ matrix.dockerfile }}" | sed 's/Dockerfile\.//')
          BRANCH=$(echo "${GITHUB_REF##*/}" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-8 | tr '[:upper:]' '[:lower:]')
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')

          echo "tag1=ghcr.io/${REPO}:${FILE_NAME}-${BRANCH}-latest" >> $GITHUB_OUTPUT
          echo "tag2=ghcr.io/${REPO}:${FILE_NAME}-${BRANCH}-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ steps.vars.outputs.tag1 }}
            ${{ steps.vars.outputs.tag2 }}

