name: Build and Push All Dockerfiles

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerfile:
          - dockerfiles/mamba.Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Sanitize Dockerfile name
        id: sanitize
        run: |
          NAME=$(basename "${{ matrix.dockerfile }}" | sed 's/\.Dockerfile$//' | tr '/' '-' | tr '.' '-')
          echo "name=$NAME" >> $GITHUB_OUTPUT

      - name: Extract metadata for image tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}
          tags: |
            type=raw,value=${{ github.ref_name }}-${{ steps.sanitize.outputs.name }}
            type=raw,value=${{ steps.sanitize.outputs.name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

